### ISSUE TITLE
長時間の接続時に切れることがある…Error: read ECONNRESET

### ISSUE THREAD

**Issue by 59naga** [59naga/nicolive.io#1]
``` bash
# Listen to http://localhost:59798
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
  at exports._errnoException (util.js:746:11)
  at TCP.onread (net.js:559:26)
```

**Comment by 59naga** [comment]
![2015-07-13 09 35 29](https://cloud.githubusercontent.com/assets/1548478/8640887/ae278f0c-2942-11e5-84cf-24604ec7f86c.png)
